main: udpechoserver.c udpechoclient.c
	gcc -Wall -o udpechoserver udpechoserver.c
	gcc -Wall -o udpechoclient udpechoclient.c

udpechoserver: 
	gcc -Wall -o udpechoserver udpechoserver.c

udpechoclient: 
	gcc -Wall -o udpechoclient udpechoclient.c

clean:
	rm -f udpechoserver udpechoclient
